package edu.uv.model.pojos;
// Generated 06-may-2014 20:27:14 by Hibernate Tools 3.2.1.GA



/**
 * ExamenesgeneradosHasPreguntaId generated by hbm2java
 */
public class ExamenesgeneradosHasPreguntaId  implements java.io.Serializable {


     private int examenesGeneradosIdexamenesGenerados;
     private int preguntaIdPregunta;

    public ExamenesgeneradosHasPreguntaId() {
    }

    public ExamenesgeneradosHasPreguntaId(int examenesGeneradosIdexamenesGenerados, int preguntaIdPregunta) {
       this.examenesGeneradosIdexamenesGenerados = examenesGeneradosIdexamenesGenerados;
       this.preguntaIdPregunta = preguntaIdPregunta;
    }
   
    public int getExamenesGeneradosIdexamenesGenerados() {
        return this.examenesGeneradosIdexamenesGenerados;
    }
    
    public void setExamenesGeneradosIdexamenesGenerados(int examenesGeneradosIdexamenesGenerados) {
        this.examenesGeneradosIdexamenesGenerados = examenesGeneradosIdexamenesGenerados;
    }
    public int getPreguntaIdPregunta() {
        return this.preguntaIdPregunta;
    }
    
    public void setPreguntaIdPregunta(int preguntaIdPregunta) {
        this.preguntaIdPregunta = preguntaIdPregunta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExamenesgeneradosHasPreguntaId) ) return false;
		 ExamenesgeneradosHasPreguntaId castOther = ( ExamenesgeneradosHasPreguntaId ) other; 
         
		 return (this.getExamenesGeneradosIdexamenesGenerados()==castOther.getExamenesGeneradosIdexamenesGenerados())
 && (this.getPreguntaIdPregunta()==castOther.getPreguntaIdPregunta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getExamenesGeneradosIdexamenesGenerados();
         result = 37 * result + this.getPreguntaIdPregunta();
         return result;
   }   


}


