package edu.uv.model.pojos;
// Generated 06-may-2014 20:27:14 by Hibernate Tools 3.2.1.GA



/**
 * ExamenesgeneradosHasPregunta generated by hbm2java
 */
public class ExamenesgeneradosHasPregunta  implements java.io.Serializable {


     private ExamenesgeneradosHasPreguntaId id;
     private Examenesgenerados examenesgenerados;
     private Pregunta pregunta;
     private Integer puntaje;

    public ExamenesgeneradosHasPregunta() {
    }

	
    public ExamenesgeneradosHasPregunta(ExamenesgeneradosHasPreguntaId id, Examenesgenerados examenesgenerados, Pregunta pregunta) {
        this.id = id;
        this.examenesgenerados = examenesgenerados;
        this.pregunta = pregunta;
    }
    public ExamenesgeneradosHasPregunta(ExamenesgeneradosHasPreguntaId id, Examenesgenerados examenesgenerados, Pregunta pregunta, Integer puntaje) {
       this.id = id;
       this.examenesgenerados = examenesgenerados;
       this.pregunta = pregunta;
       this.puntaje = puntaje;
    }
   
    public ExamenesgeneradosHasPreguntaId getId() {
        return this.id;
    }
    
    public void setId(ExamenesgeneradosHasPreguntaId id) {
        this.id = id;
    }
    public Examenesgenerados getExamenesgenerados() {
        return this.examenesgenerados;
    }
    
    public void setExamenesgenerados(Examenesgenerados examenesgenerados) {
        this.examenesgenerados = examenesgenerados;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Integer getPuntaje() {
        return this.puntaje;
    }
    
    public void setPuntaje(Integer puntaje) {
        this.puntaje = puntaje;
    }




}


