package edu.uv.model.pojos;
// Generated 06-may-2014 20:27:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Experieciaeducativa generated by hbm2java
 */
public class Experieciaeducativa  implements java.io.Serializable {


     private Integer idExperieciaEducativa;
     private Academia academia;
     private String nombreEe;
     private Set unidadeses = new HashSet(0);
     private Set personals = new HashSet(0);

    public Experieciaeducativa() {
    }

	
    public Experieciaeducativa(Academia academia, String nombreEe) {
        this.academia = academia;
        this.nombreEe = nombreEe;
    }
    public Experieciaeducativa(Academia academia, String nombreEe, Set unidadeses, Set personals) {
       this.academia = academia;
       this.nombreEe = nombreEe;
       this.unidadeses = unidadeses;
       this.personals = personals;
    }
   
    public Integer getIdExperieciaEducativa() {
        return this.idExperieciaEducativa;
    }
    
    public void setIdExperieciaEducativa(Integer idExperieciaEducativa) {
        this.idExperieciaEducativa = idExperieciaEducativa;
    }
    public Academia getAcademia() {
        return this.academia;
    }
    
    public void setAcademia(Academia academia) {
        this.academia = academia;
    }
    public String getNombreEe() {
        return this.nombreEe;
    }
    
    public void setNombreEe(String nombreEe) {
        this.nombreEe = nombreEe;
    }
    public Set getUnidadeses() {
        return this.unidadeses;
    }
    
    public void setUnidadeses(Set unidadeses) {
        this.unidadeses = unidadeses;
    }
    public Set getPersonals() {
        return this.personals;
    }
    
    public void setPersonals(Set personals) {
        this.personals = personals;
    }




}


