package edu.uv.model.pojos;
// Generated 06-may-2014 20:27:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Personal generated by hbm2java
 */
public class Personal  implements java.io.Serializable {


     private int numeroPersonal;
     private String nombre;
     private Set usuarioses = new HashSet(0);
     private Set academias = new HashSet(0);
     private Set experieciaeducativas = new HashSet(0);
     private Set examenesgeneradoses = new HashSet(0);

    public Personal() {
    }

	
    public Personal(int numeroPersonal, String nombre) {
        this.numeroPersonal = numeroPersonal;
        this.nombre = nombre;
    }
    public Personal(int numeroPersonal, String nombre, Set usuarioses, Set academias, Set experieciaeducativas, Set examenesgeneradoses) {
       this.numeroPersonal = numeroPersonal;
       this.nombre = nombre;
       this.usuarioses = usuarioses;
       this.academias = academias;
       this.experieciaeducativas = experieciaeducativas;
       this.examenesgeneradoses = examenesgeneradoses;
    }
   
    public int getNumeroPersonal() {
        return this.numeroPersonal;
    }
    
    public void setNumeroPersonal(int numeroPersonal) {
        this.numeroPersonal = numeroPersonal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }
    public Set getAcademias() {
        return this.academias;
    }
    
    public void setAcademias(Set academias) {
        this.academias = academias;
    }
    public Set getExperieciaeducativas() {
        return this.experieciaeducativas;
    }
    
    public void setExperieciaeducativas(Set experieciaeducativas) {
        this.experieciaeducativas = experieciaeducativas;
    }
    public Set getExamenesgeneradoses() {
        return this.examenesgeneradoses;
    }
    
    public void setExamenesgeneradoses(Set examenesgeneradoses) {
        this.examenesgeneradoses = examenesgeneradoses;
    }




}


