package edu.uv.model.pojos;
// Generated 06-may-2014 20:27:14 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Unidades generated by hbm2java
 */
public class Unidades  implements java.io.Serializable {


     private Integer idUnidades;
     private Experieciaeducativa experieciaeducativa;
     private String nombre;
     private Set temases = new HashSet(0);

    public Unidades() {
    }

	
    public Unidades(Experieciaeducativa experieciaeducativa, String nombre) {
        this.experieciaeducativa = experieciaeducativa;
        this.nombre = nombre;
    }
    public Unidades(Experieciaeducativa experieciaeducativa, String nombre, Set temases) {
       this.experieciaeducativa = experieciaeducativa;
       this.nombre = nombre;
       this.temases = temases;
    }
   
    public Integer getIdUnidades() {
        return this.idUnidades;
    }
    
    public void setIdUnidades(Integer idUnidades) {
        this.idUnidades = idUnidades;
    }
    public Experieciaeducativa getExperieciaeducativa() {
        return this.experieciaeducativa;
    }
    
    public void setExperieciaeducativa(Experieciaeducativa experieciaeducativa) {
        this.experieciaeducativa = experieciaeducativa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getTemases() {
        return this.temases;
    }
    
    public void setTemases(Set temases) {
        this.temases = temases;
    }




}


